- name: Set up domains.tasuki (@handshake)
  hosts: all
  vars:
    repo: https://github.com/tasuki/domains.git
    chdir: /var/www/tasuki/domains
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml

    - name: Install Elm
      import_tasks: ../tasks/install-elm.yml

    - name: "Check whether {{ chdir }}/domains.js exists"
      stat:
        path: "{{ chdir }}/domains.js"
      register: generated_js
    - name: Make
      make:
        chdir: "{{ chdir }}"
      when: not generated_js.stat.exists
