- name: Install Elm and dependencies
  become: true
  block:
    - name: Download Elm 0.19.1
      shell: "curl -L https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz | gunzip > elm"
      args:
        creates: elm

    - name: Copy the elm binary into PATH
      copy:
        src: elm
        remote_src: true
        dest: /usr/local/bin/elm
        mode: '0755'

    - name: Uglifier
      apt:
        pkg: [ uglifyjs ]
